ALTER TABLE people ADD COLUMN IF NOT EXISTS photo_url TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS phone TEXT;
ALTER TABLE people ADD COLUMN IF NOT EXISTS birth_date DATE;
ALTER TABLE people ADD COLUMN IF NOT EXISTS notes TEXT;
